### ISSUE TITLE
NCP 세팅

### ISSUE THREAD

**Issue by justwaves** [f-lab-edu/develect#11]
## Issue Description

- Naver Cloud Platform 서버를 생성하고 서버 환경을 세팅합니다

## Todo List
- [x] Centos 7.8 서버 생성
- [x] Nginx 세팅
- [x] Node.js 설치
- [x] MySQL 설치, 외부 접근 테스트
- [x] Docker 설치

**Comment by f-lab-ethan** [comment]
Sentry 설치는 필요한 시점에 진행 예정이실까요?

**Comment by justwaves** [comment]
세팅 관련 내용 노션 멘토링 페이지에 작성해두었습니다!

**Comment by f-lab-ethan** [comment]
호스트 운영체제에 nodejs 버전을 프로젝트와 동일한 18.12.1 버전으로 맞추면 좋을 것 같습니다

**Comment by justwaves** [comment]
Centos7에서 GLIBC 라이브러리 호환성 문제로 node v18을 지원하지 않는 것 같습니다
라이브러리를 따로 설치하는 방법은 다른 문제가 생길 위험이 있으니 권장하지 않고 있네요

centos7에서 다른 OS로 변경하거나 docker를 띄워 설치해야 할 것 같은데 
다른 방법이 있을까요?

참고:
https://github.com/nodejs/node/issues/43246
https://stackoverflow.com/questions/59145051/glibc-2-27-not-found-ubuntu-16-04
https://centosfaq.org/centos/nodejs-18-on-centos-7/

**Comment by f-lab-ethan** [comment]
이런 이슈가 있군요..
미리 파악하지 못했던 점 죄송합니다

NCP에서 제공하는 centos 이미지가 전부 7 버전대여서 nodejs는 도커 환경으로만 사용해야 될 것 같네요
아니면 프로젝트 전체적으로 nodejs 버전을 16 또는 17 버전으로 내리고 진행하는 것도 방법일 것 같습니다

cent 7.8에서 nodejs 17.9.1 버전까지는 정상 설치 확인했습니다

**Comment by justwaves** [comment]
네 그럼 일단 17 버전으로 진행하겠습니다!
