### ISSUE TITLE
Next.js API Routes 세팅 및 데이터베이스 연동

### ISSUE THREAD

**Issue by justwaves** [f-lab-edu/develect#19]
## Issue Description 

- Next.js의 API Routes를 구성하고 데이터베이스를 연동합니다

## Todo List 

- [ ] API Routes setup
- [ ] 데이터베이스 연결
- [ ] DB migration 파일 작성
- [ ] 테스트 API 생성

**Comment by justwaves** [comment]
@f-lab-ethan
이 이슈에서 Raw SQL 쿼리를 작성하는 방식으로 데이터베이스 작업을 진행하려고 했는데
제가 익숙하지 않아서인지 Migration 데이터나 Entity 관리가 어려운 부분이 있네요..
아무래도 ORM을 사용해서 진행하는 편이 나을 것 같은데 괜찮을까요?

**Comment by f-lab-ethan** [comment]
네 BE 관련 작업은 최소화해주시는게 좋을 것 같습니다

**Comment by justwaves** [comment]
네 알겠습니다!
