### ISSUE TITLE
Next App 생성 & PR, Issue 템플릿, 리드미 초안 작성

### ISSUE THREAD

**Issue by justwaves** [f-lab-edu/develect#9]
## Issue Description

- 현재 Repo에 Next.js 프로젝트를 생성하고 리드미 초안을 작성합니다

## Todo List
- [ ] Next.js 프로젝트 생성
- [ ] 리드미 초안 작성
- [ ] PR, Issue template 생성

**Comment by f-lab-ethan** [comment]
각 이슈에 마일스톤 레이블 추가해서 달아주면 어떨까요?

**Comment by justwaves** [comment]
네 그렇게 하겠습니다!
